version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - aws s3 mb s3://file-artifactbucket
      - sam build
      - sam deploy --stack-name file-processing-stack --s3-bucket file-artifactbucket --region us-east-1 --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM
