version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - aws s3 mb s3://file-azamlambdabucket
      - sam build
      - sam deploy --stack-name file-processing-stack --s3-bucket file-azamlambdabucket --region eu-central-1 --no-confirm-changeset --role-arn arn:aws:iam::$ACCOUNT_ID:role/cloudformationrole --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM
